name: Brasileirão Pipeline

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Rodar pipeline
        env:
          DB_HOST:     ${{ secrets.DB_HOST }}
          DB_USER:     ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME:     ${{ secrets.DB_NAME }}
          DB_PORT:     ${{ secrets.DB_PORT }}
        run: python scheduler.py --run-now

      - name: Publicar dashboard
        uses: actions/upload-artifact@v4
        with:
          name: dashboard
          path: brasileirao_dashboard.html
